config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users

  root :to => "projects#index"

  resources :projects do
    resources :tickets
  end

  namespace :admin do
    root to:"base#index"
    resources :users do
      resources :permissions
    end
  end

  match '/admin/users/:user_id/permissions', to:'admin/permissions#update', :as => :update_user_permissions

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user.permissions.each do |permission|
      can permission.action.to_sym, permission.resource_type.constantize do
        permission.resource.nil? || permission.resource_id.nil? || permission.resource_id = ""
      end
    end
  end
end

app/models/permission.rb
class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :resource, :polymorphic => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tickets
  has_many :permissions, :as => :resource
  validates :name, presence:true

  scope :readable_by, lambda { |user|
    joins(:permissions).where(:permissions => {:action => "view", :user_id => user})
  }

  def self.for(user)
    user.admin? ? Project : Project.readable_by(user)
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :title, presence:true
  validates :description, presence:true, length:{minimum:10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :tickets
  has_many :permissions

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def to_s
    "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_filter :authorize_admin!

  def index
  end
end

app/controllers/admin/permissions_controller.rb
class Admin::PermissionsController < Admin::BaseController
  before_filter :find_user

  def index
    @ability = Ability.new(@user)
    @projects = Project.all
  end

  def update
    @user.permissions.clear
    params[:permissions].each do |id, permissions|
      project = Project.find(id)
      permissions.each do |permission, checked|
        Permission.create!(:user => @user, :resource => project, :action => permission) 
      end
    end
    redirect_to admin_user_permissions_path, notice:"Permissions updated."
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.all(:order => "email")
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    set_admin
    if @user.save
      redirect_to admin_users_path, notice:"User has been created."
    else
      flash[:alert]="User has not been created."
      render action:"new"
    end
  end

  def show

  end

  def edit

  end

  def update
    if params[:user][:password].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    set_admin 
    if @user.update_attributes(params[:user])
      redirect_to admin_users_path, notice:"User has been updated."
    else
      flash[:alert] = "User has not been updated."
      render action:"edit"
    end
  end

  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end

  private
  
  def set_admin
    @user.admin = params[:user][:admin] == "1"
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      redirect_to root_path, alert:"You must be an admin to do that."
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]
  before_filter :authenticate_user!, :only => [:index, :show]
  before_filter :find_project, :only => [:show, :edit, :update, :destroy]

  def index
    @projects = Project.for(current_user).all
  end
  def new
    @project = Project.new
  end
  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, notice:"Project has been created."
    else
      flash[:alert] = "Project has not been created"
      render action:"new"
    end
  end
  def show
  end
  def edit
  end
  def update
    if @project.update_attributes(params[:project])
      redirect_to @project, notice:"Project has been updated."
    else
      flash[:alert] = "Project has not been updated."
      render action:"edit"
    end
  end
  def destroy
    @project.destroy
    redirect_to projects_path, notice:"Project has been deleted."
  end

  private
    def find_project
      @project = Project.for(current_user).find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, alert:"The project you were looking for could not be found."
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_project
  before_filter :find_ticket, only:[:show, :edit, :update, :destroy]
  before_filter :authorize_create!, only:[:new, :create]
  before_filter :authorize_update!, only:[:edit, :update]
  before_filter :authorize_delete!, only:[:destroy]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
    if @ticket.save
      redirect_to [@project, @ticket], notice:"Ticket has been created."
    else
      flash[:alert] = "Ticket has not been created."
      render action:"new"
    end
  end

  def edit
  end

  def update
    if @ticket.update_attributes(params[:ticket])
      redirect_to [@project, @ticket], notice:"Ticket has been updated."
    else
      flash[:alert] = "Ticket has not been updated."
      render action:"edit"
    end
  end

  def destroy
    @ticket.destroy
    redirect_to @project, notice:"Ticket has been deleted."
  end

  private
    def find_project
      @project = Project.for(current_user).find(params[:project_id])
      rescue ActiveRecord::RecordNotFound
        redirect_to root_path, alert:"The project you were looking for could not be found."
    end
    
    def find_ticket
      @ticket = @project.tickets.find(params[:id])
    end

    def authorize_create!
      if !current_user.admin? && cannot?("create tickets".to_sym, @project)
        redirect_to @project, alert:"You are not allowed to create tickets on this project."
      end
    end

    def authorize_update!
      if !current_user.admin? && cannot?("edit tickets".to_sym, @project)
        redirect_to @project, alert:"You are not allowed to edit tickets on this project."
      end
    end

    def authorize_delete!
      if !current_user.admin? && cannot?("delete tickets".to_sym, @project)
        redirect_to @project, alert:"You are not allowed to delete tickets in this project."
      end
    end
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
  def permissions
    {"view"=>"View",
      "create tickets"=>"Create Tickets",
      "edit tickets" => "Edit Tickets",
      "delete tickets" => "Delete Tickets"}
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    @title = (parts << "Ticketee").join(" - ") unless parts.empty?
    @title || "Ticketee"
  end

  def admins_only(&block)
    block.call if current_user && current_user.admin?
    nil
  end

  def authorized?(permission, resource, &block)
    block.call if can?(permission.to_sym, resource) || current_user.try(:admin?)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/base/index.html.haml
= link_to "Users", admin_users_path
Welcome to Ticketee's Admin Lounge.  Please enjoy your stay.

app/views/admin/permissions/index.html.haml
%h2 Permissions for
= @user.email

= form_tag update_user_permissions_path, :method => :put do
  %table
    %thead
      - permissions.each do |name, text|
        %th= text
    %tbody
      - @projects.each do |project|
        %tr
          %td= project.name
          - permissions.each do |name, text|
            %td= check_box_tag "permissions[#{project.id}][#{name}]", @ability.can?(name.to_sym, project)

  = submit_tag "Update"

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  = f.error_messages
  %p
    = f.label :email
    = f.text_field :email

  %p
    = f.label :password
    = f.password_field :password

  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  %p
    = f.check_box :admin
    = f.label :admin, "Is an admin?"

  = f.submit

app/views/admin/users/edit.html.haml
= render "form"

app/views/admin/users/index.html.haml
= link_to "New User", new_admin_user_path
%ul
  - @users.each do |user|
    %li= link_to user, [:admin, user]

app/views/admin/users/new.html.haml
= render "form"

app/views/admin/users/show.html.haml
%h2= @user
= link_to "Edit", edit_admin_user_path(@user)
= link_to "Delete", admin_user_path(@user), :method => :delete, :confirm => "Are you sure you want to delete this user?"
= link_to "Permissions", admin_user_permissions_path(@user)

app/views/layouts/application.html.haml
%head
  %title= title
  = stylesheet_link_tag :all 
  = javascript_include_tag :defaults 
  = csrf_meta_tag 
%body
  - flash.each do |key, value|
    .flash{:id=> key}
      = value

  %h1= link_to "Ticketee", root_path
  %nav
    - if !user_signed_in?
      = link_to "Sign up", new_user_registration_path
      = link_to "Sign in", new_user_session_path
    - else
      Signed in as
      = current_user.email
      = link_to "Sign out", destroy_user_session_path
    - admins_only do
      = link_to "Admin", admin_root_path
  = yield 

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  = f.error_messages
  %p
    = f.label :name, "Project name:"
    = f.text_field :name
  = f.submit

app/views/projects/edit.html.haml
%h2 Edit project
= render "form"

app/views/projects/index.html.haml
%h2 Projects
%ul
  - @projects.each do |project|
    %li= link_to project.name, project
- admins_only do
  = link_to "New Project", new_project_path

app/views/projects/show.html.haml
- title(@project.name, "Projects")
%h2= @project.name
%menu
  - admins_only do
    = link_to "Edit", edit_project_path(@project)
    = link_to "Delete", @project, method:'delete', confirm:"Are you sure you want to delete this project?"
  = authorized?(:"create tickets", @project) do
    = link_to "New Ticket", new_project_ticket_path(@project)

%ul#tickets
  - @project.tickets.each do |ticket|
    %li= link_to "#{ticket.id} - #{ticket.title}", [@project, ticket]

app/views/tickets/_form.html.haml
= form_for [@project, @ticket] do |f|
  = f.error_messages
  %p
    = f.label :title
    %br
    = f.text_field :title
  %p
    = f.label :description
    %br
    = f.text_field :description
  = f.submit

app/views/tickets/edit.html.haml
%h2 Editing a ticket in
= @project.name
= render "form"

app/views/tickets/new.html.haml
%h2 New Ticket
= render "form"

app/views/tickets/show.html.haml
%h2= @ticket.title
%menu
  = authorized?("edit tickets", @project) do
    = link_to "Edit", [:edit, @project, @ticket]
  = authorized?('delete tickets', @project) do
    = link_to "Delete", [@project, @ticket], method:'delete', confirm:"Are you sure you want to delete this ticket?"
%small 
  Created by
  = @ticket.user.email
= simple_format(@ticket.description)